server:
  port: 8084
  servlet:
    context-path: /netdisk
    multipart:
       enabled: true
       max-file-size: 200MB
       max-request-size: 500MB

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/netdisk?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


  thymeleaf:
    enabled: true #开启试图解析
    encoding: utf-8
    prefix: classpath:/templates/ #前缀
    cache: false  #是否使用缓存
    mode: HTML   #严格的html语法模式
    suffix: .html  #后缀

mybatis-plus:
  type-aliases-package: com.dfrz.bean
  mapper-locations: classpath:mapping/*.xml

logging:
  config: classpath:logback.xml
  level:
    com.dfrz.mapper: debug

